- name: Add PPA
  become: true
  shell: "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_{{ansible_distribution_version}}/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list"
  tags:
    - install
    - albert

- name: Add PPA pt2 ?
  become: true
  shell: "curl -fsSL https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_{{ansible_distribution_version}}/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_manuelschneid3r.gpg > /dev/null"
  tags:
    - install
    - albert

- name: Install Albert
  become: true
  apt: name=albert
    update_cache: true
  tags:
    - install
    - albert
   # # 2 sudok apt update
    # 3 sudo apt install -y albert
# {{ ansible_distribution_version}}
