- name: Add PPA
  become: true
  shell: "curl -fsSL https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_{{ansible_distribution_version}}/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_manuelschneid3r.gpg > /dev/null"
  tags:
    - install
    - albert

- name: Update apt
  become: true
  apt:
    update_cache: true
    state: present
  tags:
    - install
    - albert

- name: Install Albert
  become: true
  apt: name=albert
  tags:
    - install
    - albert
