- name: Download lates Google Chrome
  get_url: url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb dest=/tmp/chrome.deb
  tags:
    - install
    - chrome
    - core

- name: Install Chrome
  become: true
  apt: deb="/tmp/chrome.deb"
  tags:
    - install
    - chrome
    - core
