- name: Install core system packages (curl, wget)
  become: true
  apt:
    name: ["curl", "wget"]
  tags:
    - core
    - nvim

- name: Install core system packages 2
  become: true
  apt:
    name: ["gettext", "htop", "dconf-editor", "python3-pip", "build-essential", "gnome-tweaks", "deja-dup", "exa", "lm-sensors", "net-tools", "snapd"]
  tags:
    - core
    - nvim

# - name: Install snaps
  # become:
    # snap:
      # ["qualculate", "spotify", ""]

# - name: Install snaps --classic
  # become:
    # snap:
      # ["intellij-idea-ultimate"]
