- name: Remove previos docker versions
  become: true
  apt:
    name: ["docker","docker-engine","docker.io","containerd","runc"]
    state: absent
  tags: &tags_docker ["docker", "install"]

- name: Adding necessary packages
  become: true
  apt:
    name: ["ca-certificates", "gnupg", "lsb-release"]
  tags: *tags_docker

- name: Adding docker GPG key
  become: true
  shell: "sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"

- name: Set up repository
  become: true
  shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  tags: *tags_docker

- name: Install Docker Engine
  become: true
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin"]
    update_cache: true
    state: present
