- name: Remove old nodejs and npm
  become: true
  apt:
    name: ["nodejs", "node", "npm"]
    state: absent
  tags:
  - install
  - node
  - lsp

- name: Add node-16.x ppa
  become: true
  shell: 'curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -'
  tags:
  - install
  - node
  - lsp

- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs"]
  tags:
  - install
  - node
  - lsp

- name: npmjs prefix
  shell: mkdir -p "{{ lookup('env', 'HOME') }}/.local/.npm-global"
  tags:
  - install
  - node
  - lsp

- name: add npmjs to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - install
  - node
  - lsp

- name: npmjs global settings
  shell: npm config set prefix "{{ lookup('env', 'HOME') }}/.local/.npm-global"
  tags:
  - install
  - node
  - lsp

- name: npmjs global settings export path in case I don't have dotfiles installed
  shell: export PATH=~/.local/.npm-global/bin:$PATH
  tags:
  - install
  - node
  - npm-path
  - lsp
