- name: Download nvim nightly releas
  get_url: url=https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz dest={{ lookup('env', 'HOME') }}/nvim-linux64.tar.gz
  tags: &tags_for_nvim [ 'install', 'nvim' ]

- name: Remove old nvim
  shell: "mv {{ lookup('env', 'HOME') }}/bin/nvim-linux64 {{ lookup('env', 'HOME') }}/bin/nvim-linux64-old"
  tags: *tags_for_nvim

- name: Install nvim nightly
  shell: "tar xzvf {{ lookup('env', 'HOME') }}/nvim-linux64.tar.gz -C {{ lookup('env', 'HOME') }}/bin"
  tags: *tags_for_nvim

- name: Check that the somefile.conf exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  register: packer_stats
  tags: *tags_for_nvim

- name: Install packer
  shell: "git clone --depth 1 https://github.com/wbthomason/packer.nvim  {{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  when: packer_stats.stat.exists == False
  tags: ['install', 'nvim', 'packer']
