- name: Install Java
  become: true
  apt:
    name: ["openjdk-8-jdk", "default-jdk", "default-jre"]
  tags:
    - dev
    - scala
    - java
- name: Download Coursier
  get_url: url=https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz dest=/tmp/cs.gz
  tags:
    - dev
    - scala
- name: Unpack Coursier installation
  command: gzip -d -f /tmp/cs.gz
  tags:
    - dev
    - scala
- name: Add execution privlage
  command: chmod +x /tmp/cs
  tags:
    - dev
    - scala
- name: Install Coursier (cs, scala-cli, scala, scalac, sbt, ammonite, scalafmt)
  command: /tmp/cs setup --yes
  tags:
    - dev
    - scala
